timestamp: 2025-03-08T21:43:42.195384
process title: pantsd [/mnt/c/Users/David/Apps-Start/Start-App/start-mono-seed]
sys.argv: ['/home/david/.cache/nce/6d61748cea187199dc28418157b2121ccbbb44e4af2ee6fddf8c04bbed73f76d/bindings/venvs/2.24.0/bin/pants', '-ldebug', '--no-local-cache', 'run', 'apps/django-app:manage', '--', 'runserver', '--noreload']
pid: 4264
Signal 15 (SIGTERM) was raised. Exiting with failure.
  File "/home/david/.cache/nce/6d61748cea187199dc28418157b2121ccbbb44e4af2ee6fddf8c04bbed73f76d/bindings/venvs/2.24.0/bin/pants", line 16, in <module>
    sys.exit(entry_point())
  File "/home/david/.cache/nce/6d61748cea187199dc28418157b2121ccbbb44e4af2ee6fddf8c04bbed73f76d/bindings/venvs/2.24.0/lib/python3.9/site-packages/pants/bin/pants_loader.py", line 114, in main
    PantsLoader.main()
  File "/home/david/.cache/nce/6d61748cea187199dc28418157b2121ccbbb44e4af2ee6fddf8c04bbed73f76d/bindings/venvs/2.24.0/lib/python3.9/site-packages/pants/bin/pants_loader.py", line 108, in main
    cls.run_alternate_entrypoint(entrypoint)
  File "/home/david/.cache/nce/6d61748cea187199dc28418157b2121ccbbb44e4af2ee6fddf8c04bbed73f76d/bindings/venvs/2.24.0/lib/python3.9/site-packages/pants/bin/pants_loader.py", line 85, in run_alternate_entrypoint
    entrypoint_fn()
  File "/home/david/.cache/nce/6d61748cea187199dc28418157b2121ccbbb44e4af2ee6fddf8c04bbed73f76d/bindings/venvs/2.24.0/lib/python3.9/site-packages/pants/pantsd/pants_daemon.py", line 238, in launch_new_pantsd_instance
    daemon.run_sync()
  File "/home/david/.cache/nce/6d61748cea187199dc28418157b2121ccbbb44e4af2ee6fddf8c04bbed73f76d/bindings/venvs/2.24.0/lib/python3.9/site-packages/pants/pantsd/pants_daemon.py", line 211, in run_sync
    time.sleep(self.JOIN_TIMEOUT_SECONDS)
  File "/home/david/.cache/nce/6d61748cea187199dc28418157b2121ccbbb44e4af2ee6fddf8c04bbed73f76d/bindings/venvs/2.24.0/lib/python3.9/site-packages/pants/base/exception_sink.py", line 109, in handle_sigterm
    raise self.SignalHandledNonLocalExit(signum, "SIGTERM")
  File "/home/david/.cache/nce/6d61748cea187199dc28418157b2121ccbbb44e4af2ee6fddf8c04bbed73f76d/bindings/venvs/2.24.0/lib/python3.9/site-packages/pants/base/exception_sink.py", line 94, in __init__
    self.traceback_lines = traceback.format_stack()

Fatal Python error: Aborted

Thread 0x00007f56260dc740 (most recent call first):
<no Python frame>
